INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'08e3b5a6-9cbc-418e-a56b-24cdcb33f3a3', N'2021-05-23 16:37:50.8324325', N'25b04edc-554c-4cbc-a5dc-a58aa3d09710', N'1', N'2');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'1', N'2021-04-28 13:19:15.0000000', N'25b04edc-554c-4cbc-a5dc-a58aa3d09710', N'Проект №1', N'  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sagittis rhoncus dui, at varius odio mollis vitae. Sed ac dolor dolor. Integer eget ex id tellus venenatis dapibus. Pellentesque vestibulum, nunc sit amet commodo vestibulum, mi leo mattis sem, ut feugiat ligula dui eget nulla. Aliquam nec posuere sem. In vitae gravida neque, vel varius arcu. Nullam in eros sit amet tellus posuere lobortis. Donec mollis rhoncus scelerisque. Duis maximus neque nunc, at ultricies dui finibus sit amet. Cras vitae arcu leo.  Nullam vitae sapien justo. Maecenas odio massa, sodales sit amet odio id, tempus gravida ante. Curabitur ultricies egestas enim, sit amet mollis nisi pretium et. Aliquam imperdiet facilisis metus id ullamcorper. Cras at posuere lacus. Aenean aliquet imperdiet pulvinar. Nullam nec diam neque. Donec non ante non lectus iaculis pretium non vel magna. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'1e3f6562-a6b9-404d-82ca-465e9eb9e7d7', N'2021-05-22 13:34:56.2727842', N'5a73781f-2288-4d04-a36a-99702716cefb', N'3', N'

Sed nulla dolor, maximus at vestibulum quis, egestas id libero. Suspendisse tempor leo magna, vel tristique est malesuada et. Quisque sed nulla eget ipsum vehicula ultrices. Aliquam sed orci et tellus feugiat fermentum in in lacus. Etiam lacinia posuere turpis. Nulla facilisi. Fusce quis sapien rhoncus, semper purus vitae, laoreet odio. Aliquam in lectus at nunc commodo tempor.

Nunc egestas et ex non imperdiet. Suspendisse eget eleifend orci. Fusce efficitur sagittis odio, sit amet condimentum nunc congue a. Nulla placerat sit amet lacus nec suscipit. Praesent accumsan ex in sagittis aliquam. Nulla maximus euismod massa ac tincidunt. Vestibulum tincidunt iaculis ante rhoncus fermentum. Aliquam erat volutpat. Aenean eleifend risus consectetur, consequat diam ut, feugiat libero. Morbi augue est, efficitur at bibendum in, laoreet quis leo. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'43660768-b48c-4657-affd-ec6ae83f3296', N'2021-05-22 13:36:40.9834127', N'5a73781f-2288-4d04-a36a-99702716cefb', N'8', N'

Quisque vitae laoreet dui. Mauris facilisis, magna eu sodales feugiat, sem purus porta nisl, ac convallis ligula augue nec sapien. Sed tincidunt felis sit amet leo iaculis, in tristique felis porttitor. Mauris iaculis nec arcu et bibendum. Cras finibus euismod diam et malesuada. Sed luctus mattis urna ut ullamcorper. Phasellus eleifend justo eu orci tempor, sed blandit justo vulputate. Maecenas accumsan et sapien et sodales. Aliquam erat volutpat. Maecenas commodo tortor ac cursus euismod.

Duis at suscipit sem. Nullam blandit mi id commodo cursus. Mauris vel leo sit amet dolor euismod scelerisque in dapibus tortor. Proin euismod metus non tellus semper, in congue lectus feugiat. Aenean velit neque, semper ut egestas euismod, ornare ac ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam sit amet purus eget est fermentum maximus. Vestibulum semper metus lacus, quis tempus lacus efficitur ac. Sed id dolor at tellus venenatis commodo.

Nunc molestie risus a mi varius, vel efficitur metus iaculis. Fusce eros nisl, euismod ac turpis finibus, aliquet vehicula risus. Donec bibendum dapibus lectus vitae ornare. Nulla lacus mauris, imperdiet quis convallis sit amet, faucibus in est. Morbi aliquet rhoncus fringilla. Duis imperdiet venenatis risus. Pellentesque quam ex, sagittis eu sollicitudin eu, lobortis nec justo. Vivamus bibendum nisi eget blandit mollis. Mauris urna sem, vestibulum sed orci non, euismod mollis nisi. Maecenas laoreet tristique convallis.

Nullam convallis dictum nisi id tempus. Quisque nec finibus diam. Ut in turpis ut neque lobortis dignissim et nec odio. Fusce mauris metus, rhoncus id porttitor a, imperdiet et libero. Donec sed porta tortor, id eleifend enim. Aliquam non interdum dolor. Fusce blandit, augue a maximus pellentesque, nulla arcu ultricies tellus, a sodales augue odio vel magna. Aliquam erat volutpat. Morbi mattis vestibulum tortor, sed interdum leo maximus sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed diam sit amet nulla tempor porta. Nunc enim nisl, laoreet quis commodo et, lacinia quis urna. Nulla pulvinar arcu elit. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'509f9518-88cc-4483-ade5-d37059a5d129', N'2021-05-21 11:01:12.0573146', N'5a73781f-2288-4d04-a36a-99702716cefb', N'Проект 2', N'Nullam eu facilisis eros. Cras fermentum enim molestie augue cursus, et gravida libero luctus. Pellentesque eget risus eu diam consectetur auctor. Curabitur at placerat lacus. Donec commodo ipsum molestie velit fringilla, sit amet posuere est vestibulum. Ut cursus metus eu augue vulputate, sed placerat nibh cursus. Maecenas pretium rutrum quam, ut vehicula urna lacinia in. Ut quis lectus et erat rutrum eleifend. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'5af23fa6-483c-4711-8569-f9de6c2b1398', N'2021-05-22 12:55:12.9918905', N'5a73781f-2288-4d04-a36a-99702716cefb', N'Альфа', N'123456789


Павлик');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'5f5cc998-ab73-48f8-a7b8-05f2c51ea512', N'2021-05-31 08:03:48.7638619', N'eb9b65d6-4c58-4e97-a284-a3a1fb8b778f', N'1', N'1');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'706b7529-ebed-4ae7-baa7-3b88b44a5baa', N'2021-05-22 13:35:22.9245187', N'5a73781f-2288-4d04-a36a-99702716cefb', N'5', N'

Sed nulla dolor, maximus at vestibulum quis, egestas id libero. Suspendisse tempor leo magna, vel tristique est malesuada et. Quisque sed nulla eget ipsum vehicula ultrices. Aliquam sed orci et tellus feugiat fermentum in in lacus. Etiam lacinia posuere turpis. Nulla facilisi. Fusce quis sapien rhoncus, semper purus vitae, laoreet odio. Aliquam in lectus at nunc commodo tempor.

Nunc egestas et ex non imperdiet. Suspendisse eget eleifend orci. Fusce efficitur sagittis odio, sit amet condimentum nunc congue a. Nulla placerat sit amet lacus nec suscipit. Praesent accumsan ex in sagittis aliquam. Nulla maximus euismod massa ac tincidunt. Vestibulum tincidunt iaculis ante rhoncus fermentum. Aliquam erat volutpat. Aenean eleifend risus consectetur, consequat diam ut, feugiat libero. Morbi augue est, efficitur at bibendum in, laoreet quis leo. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'a0ef6b59-df89-4fd2-a112-ba5b05405eff', N'2021-05-22 13:36:10.8863713', N'5a73781f-2288-4d04-a36a-99702716cefb', N'7', N'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam ut leo convallis, tristique quam vestibulum, ultrices diam. Nunc neque velit, vestibulum eget vehicula sed, feugiat eu turpis. Curabitur tempus semper eleifend. Proin neque quam, ultricies vel facilisis in, tincidunt in est. Proin in ligula ut quam egestas commodo. Suspendisse eleifend libero sem, in maximus ante iaculis vel. Donec luctus massa molestie tellus dapibus scelerisque. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'c3e912ab-e226-4731-a3a7-a87a5fe7d3b9', N'2021-05-22 13:35:11.5866009', N'5a73781f-2288-4d04-a36a-99702716cefb', N'4', N'

Sed nulla dolor, maximus at vestibulum quis, egestas id libero. Suspendisse tempor leo magna, vel tristique est malesuada et. Quisque sed nulla eget ipsum vehicula ultrices. Aliquam sed orci et tellus feugiat fermentum in in lacus. Etiam lacinia posuere turpis. Nulla facilisi. Fusce quis sapien rhoncus, semper purus vitae, laoreet odio. Aliquam in lectus at nunc commodo tempor.

Nunc egestas et ex non imperdiet. Suspendisse eget eleifend orci. Fusce efficitur sagittis odio, sit amet condimentum nunc congue a. Nulla placerat sit amet lacus nec suscipit. Praesent accumsan ex in sagittis aliquam. Nulla maximus euismod massa ac tincidunt. Vestibulum tincidunt iaculis ante rhoncus fermentum. Aliquam erat volutpat. Aenean eleifend risus consectetur, consequat diam ut, feugiat libero. Morbi augue est, efficitur at bibendum in, laoreet quis leo. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'ce0b88a4-c64d-42d3-893b-dc9b6375957a', N'2021-05-22 13:37:05.7863189', N'5a73781f-2288-4d04-a36a-99702716cefb', N'9', N'Sed suscipit elit lacus, ut dapibus lorem gravida eu. Sed fermentum risus nec risus pharetra suscipit. In vitae ligula id lectus rutrum interdum ut eget orci. Cras auctor tempus libero, a tristique nulla ornare vel. Phasellus sed velit non purus malesuada sollicitudin et sed leo. Praesent sit amet risus eget nisl consectetur iaculis quis ac urna. Sed a fermentum lorem. Sed pharetra luctus pretium. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'd6ff5b9f-f7b7-45e8-ac7f-196a12cdd2f9', N'2021-05-28 11:53:35.6718020', N'905ce28a-7192-4981-b0f9-20b4d3cdbc76', N'1', N'1');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'eccf40d8-1dba-422f-9bde-348135aab845', N'2021-05-22 13:34:45.6765856', N'5a73781f-2288-4d04-a36a-99702716cefb', N'2', N'

Sed nulla dolor, maximus at vestibulum quis, egestas id libero. Suspendisse tempor leo magna, vel tristique est malesuada et. Quisque sed nulla eget ipsum vehicula ultrices. Aliquam sed orci et tellus feugiat fermentum in in lacus. Etiam lacinia posuere turpis. Nulla facilisi. Fusce quis sapien rhoncus, semper purus vitae, laoreet odio. Aliquam in lectus at nunc commodo tempor.

Nunc egestas et ex non imperdiet. Suspendisse eget eleifend orci. Fusce efficitur sagittis odio, sit amet condimentum nunc congue a. Nulla placerat sit amet lacus nec suscipit. Praesent accumsan ex in sagittis aliquam. Nulla maximus euismod massa ac tincidunt. Vestibulum tincidunt iaculis ante rhoncus fermentum. Aliquam erat volutpat. Aenean eleifend risus consectetur, consequat diam ut, feugiat libero. Morbi augue est, efficitur at bibendum in, laoreet quis leo. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'ef619792-748d-4a09-a203-8bf588c93a82', N'2021-05-22 13:35:55.6480166', N'5a73781f-2288-4d04-a36a-99702716cefb', N'6', N'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam ut leo convallis, tristique quam vestibulum, ultrices diam. Nunc neque velit, vestibulum eget vehicula sed, feugiat eu turpis. Curabitur tempus semper eleifend. Proin neque quam, ultricies vel facilisis in, tincidunt in est. Proin in ligula ut quam egestas commodo. Suspendisse eleifend libero sem, in maximus ante iaculis vel. Donec luctus massa molestie tellus dapibus scelerisque. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'f778964a-b6b4-4c5f-a50e-141b7623d9c3', N'2021-05-22 13:34:33.7204287', N'5a73781f-2288-4d04-a36a-99702716cefb', N'1', N'

Sed nulla dolor, maximus at vestibulum quis, egestas id libero. Suspendisse tempor leo magna, vel tristique est malesuada et. Quisque sed nulla eget ipsum vehicula ultrices. Aliquam sed orci et tellus feugiat fermentum in in lacus. Etiam lacinia posuere turpis. Nulla facilisi. Fusce quis sapien rhoncus, semper purus vitae, laoreet odio. Aliquam in lectus at nunc commodo tempor.

Nunc egestas et ex non imperdiet. Suspendisse eget eleifend orci. Fusce efficitur sagittis odio, sit amet condimentum nunc congue a. Nulla placerat sit amet lacus nec suscipit. Praesent accumsan ex in sagittis aliquam. Nulla maximus euismod massa ac tincidunt. Vestibulum tincidunt iaculis ante rhoncus fermentum. Aliquam erat volutpat. Aenean eleifend risus consectetur, consequat diam ut, feugiat libero. Morbi augue est, efficitur at bibendum in, laoreet quis leo. ');
INSERT INTO repositorydb2.dbo.CourseProjects (Id, CreationDate, UserId, Title, Description) VALUES (N'fca4832e-068f-47bb-ac83-57a281ad882a', N'2021-05-22 14:18:27.7148399', N'5a73781f-2288-4d04-a36a-99702716cefb', N'Z', N'123');